[package]
name = "olifm-master"
version = "0.1.0"
edition = "2024"

[dependencies]
blurhash = "0.2.3"
content_service = { path = "content_service" }
image = "0.25.8"
markdown = "1.0.0"
once_cell = "1.21.3"
regex = "1.11.2"
serde = "1.0.219"
serde_json = "1.0.143"
