[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
reqwest = { version = "0.12.23", features = ["json"] }
tokio = "1.47.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
