[package]
name = "content_service"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.42"
gloo-net = "0.4"
gloo-utils = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"

[lib]
crate-type = ["rlib"]
