[package]
authors = ["Oliver Posa"]
edition = "2024"
name = "web"
publish = false
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
admin = { path = "../admin" }
wasm-bindgen = "0.2.118"
wasm-bindgen-futures = "0.4.68"
web-sys = "0.3.95"
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
